### PR TITLE
Implement Multi stage build for sdk image.

### PR DESCRIPTION
**Pull request by chimanjain**
# Description

Implement Multi stage build for sdk image.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1098 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have inspected the Grafana dashboards to verify the data is displayed properly
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?

- [x] Docker image build
Screenshot 2024-01-11 172105

- [x] Ran basic sanity test on built docker image.

### CODE REVIEW

**Comment by gallacher** [comment]
@chimanjain - are these changes required across other repositories to maintain consistency? Is there a GitHub issue these changes are associated with?

**Comment by chimanjain** [comment]
> @chimanjain - are these changes required across other repositories to maintain consistency? Is there a GitHub issue these changes are associated with?

Yes, these changes will made across all the metrics sdk images. GitHub issue has been created for these changes https://github.com/dell/csm/issues/1098.

**Review by gallacher — APPROVED** [review]

**Review by nitesh3108 — APPROVED** [review]

**Comment by nitesh3108** [comment]
e2e pass

**Review by gallacher — APPROVED** [review]

**Comment by nitesh3108** [comment]
skip e2e

**Comment by rajendraindukuri** [comment]
e2e pass

**Comment by rajendraindukuri** [comment]
skip e2e

**Review by donatwork — APPROVED** [review]

**Comment by donatwork** [comment]
e2e pass

**Comment by donatwork** [comment]
skip e2e tests

**Comment by donatwork** [comment]
skip e2e tests

**Comment by donatwork** [comment]
e2e pass

**Comment by donatwork** [comment]
e2e pass

**Comment by donatwork** [comment]
run e2e tests

**Comment by donatwork** [comment]
skip e2e tests

**Pull request merged**
